# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2341a5793ff7257d3d88b628585949f9ad80bdd7db62999838dc4c5c48ca4226f6dadd09f81aa8621e3fc0f83e12c2386b56d2828b006c174c2b3ed9515cd316

test:
  secret_key_base: 8f0dc4c6684566e2dd250979d7603946ac258aa0114ac8a1255aee39d39b6fd7ee1e8c6e17e10ccf41832fce562be651741bce8a5c6d2f69702857e0fb082668

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
